### ISSUE TITLE
Fix romanian stop words

### ISSUE THREAD

**Issue by skykery** [Alir3z4/stop-words#8]
Here is the updated list of stop words for Romanian. In our language are some words that are using "a" instead of "i" in writing.

`vreo
acelea
cata
cita
degraba
lor
alta
tot
ai
dat
despre
peste
bine
dar
foarte
avea
multi
cit
cat
alt
mai
sa
fie
tu
multe
orice
dintr
dintre
dintr-o
dintr-un
se
intr
intr-o
intr-un
niste
multa
insa
il
fost
a
abia
nimic
sub
acel
in
altceva
si
avem
altfel
c
ea
acest
li
parca
fi
dintre
unele
m
acestei
mare
cel
este
pe
atitia
atatia
uneori
acela
iti
astazi
acestui
o
imi
ele
ceilalti
pai
fata
noua
sa-ti
altul
au
i
prin
conform
aceste
anume
azi
k
unul
ala
unei
fara
ei
la
aceeasi
u
inapoi
acestea
acesta
aceasta
catre
sale
asupra
as
aceea
ba
ale
da
le
apoi
aia
suntem
cum
isi
inainte
s
de
cind
cand
cumva
chiar
acestia
daca
sunt
care
al
numai
cui
sus
tocmai
prea
cu
mi
eu
doar
niciodata
exact
putini
aiurea
tuturor
celor
astfel
atunci
citeva
cateva
cat
sau
fel
intre
acolo
nostri
ma
mult
una
ceea
iar
sintem
suntem
ati
din
geaba
sai
caruia
adica
inca
are
aici
ca
ia
nici
d
oricum
asta
carora
face
citiva
cativa
voi
unor
f
atat
toata
alaturi
cea
nu
totusi
ce
altii
acum
sint
sunt
capat
mod
deasupra
cam
vom
b
toate
careia
aceasta
atit
atat
nimeni
ii
ci
unde
ul
plus
era
sa-mi
l
spre
dupa
nou
cele
acea
un
incit
incat
n
cei
or
va
deci
acelasi
atatea
h
vor
decit
decat
noi
cineva
desi
ceva
j
ului
atitea
atatea
avut
ar
pina
pana
t
atata
unui
el
citi
asa
totul
pentru
atita
v
alti
asemenea
atatia
te
ne
deja
unii
p
atare
cite
cate
cine
cand
toti
vreun
ori
r
alte
lui
ti
ni
aceia
am`

**Comment by Alir3z4** [comment]
@skykery Could you please make a pull request for these changes ?
