### ISSUE TITLE
Fix german stop words

### ISSUE THREAD

**Issue by valentindey** [Alir3z4/stop-words#9]
`german.txt` contains wrong inflection forms of "uns".

lines 189 up to including 193 should be

    unsere
    unserem
    unseren
    unserer
    unseres

and "unser" must be added again, as I changed it to "unserer" above.

Source: german as mother tongue

**Comment by Alir3z4** [comment]
@valentindey Thanks for the contribution.
I've updated the german.txt file and applied your changes.

**Comment by valentindey** [comment]
I'm glad to help. But I think you missed adding "unser"

**Comment by Alir3z4** [comment]
Oh, you're right.
I missed that part, lemme get it fied

**Comment by Alir3z4** [comment]
Done it in https://github.com/Alir3z4/stop-words/commit/ab7b350b3199ff52f761877ed0e191f7e90837c7 thanks again
